version: "2"

services:
  targetsio:
    image: dmoll1974/targets-io
    ports:
     - "3000:3000"
    networks:
      - my-net
    environment:
       MONGO_SERVICE_HOST: "db"
       MONGO_SERVICE_PORT: "27017"
       REDIS_SERVICE_HOST: "redis"
       REDIS_SERVICE_PORT: "6379"
       GRAPHITE_SERVICE_HOST: "graphite"
       GRAPHITE_SERVICE_PORT: "80"
    restart: always
  db:
    image: mongo:3.0
    ports:
     - "27017:27017"
    networks:
      - my-net
    volumes:
     - /home/marathon/var/lib/targets-io/mongo:/data/db
    restart: always
  graphite:
    image: dmoll1974/targets-io-graphite
    networks:
      - my-net
    ports:
     - "88:80"
     - "2003:2003"
     - "8125:8125"
    volumes:
     - /home/marathon/var/lib/targets-io/graphite/log:/var/log
     - /home/marathon/var/lib/targets-io/graphite/storage:/opt/graphite/storage
    restart: always
  jenkins:
    image: jenkins
    networks:
      - my-net
    ports:
     - "8088:8080"
    restart: always
  redis:
    image: redis
    networks:
      - my-net
    ports:
     - "6379:6379"
    restart: always
networks:
  my-net:
    driver: bridge

