targetsio:
  image: dmoll1974/targets-io
  ports:
   - "3000:3000"
  volumes:
   - .:/code
  links:
   - graphite
   - db
   - memcached
  environment:
     MONGO_SERVICE_HOST: "db"
     MONGO_SERVICE_PORT: "27017"
     MONGO_CACHE_SERVICE_HOST: "db"
     MONGO_CACHE_SERVICE_PORT: "27018"
     MEMCACHED_SERVICE_HOST: "memcached"
     MEMCACHED_SERVICE_PORT: "11211"
     GRAPHITE_SERVICE_HOST: "graphite"
     GRAPHITE_SERVICE_PORT: "80"
  mem_limit: 1000000000
  restart: always
db:
  image: dmoll1974/targets-io-mongo
  ports:
   - "27017:27017"
  volumes:
   - /home/marathon/var/lib/targets-io/mongo:/data/db
  restart: always
graphite:
  image: dmoll1974/targets-io-graphite
  ports:
   - "88:80"
   - "2003:2003"
   - "8125:8125"
  volumes:
   - /home/marathon/var/lib/targets-io/graphite/log:/var/log
   - /home/marathon/var/lib/targets-io/graphite/storage:/opt/graphite/storage
  restart: always
jenkins:
  image: jenkins
  ports:
   - "8088:8080"
  links:
   - graphite
   - targetsio
  restart: always
memcached:
  image: sameersbn/memcached:latest
  ports:
   - "11211:11211"
  environment:
   CACHE_SIZE: 1024
   EXTRA_OPTS: "-I 10m"
  mem_limit: 1000000000 restart: always
  restart: always


