version: "2"

services:
  db:
    image: mongo:3.0
    ports:
     - "27017:27017"
    networks:
      - my-net
    volumes:
     - /var/lib/targets-io/mongo:/data/db
    restart: always
  graphite:
    image: dmoll1974/targets-io-graphite
    networks:
      - my-net
    ports:
     - "8090:80"
     - "2003:2003"
     - "8125:8125"
    volumes:
     - /var/lib/targets-io/graphite/log:/var/log
     - /var/lib/targets-io/graphite/storage:/opt/graphite/storage
    restart: always
  jenkins:
    image: dmoll1974/targets-io-jenkins
    networks:
      - my-net
    ports:
     - "8070:8080"
     - "50000:50000"
    restart: always
  redis:
    image: redis
    networks:
      - my-net
    ports:
     - "6379:6379"
    restart: always
  targetsio:
    image: dmoll1974/targets-io
    ports:
     - "3000:3000"
    networks:
      - my-net
    environment:
       MONGO_URL: "db:27017/targets-io"
       REDIS_SERVICE_HOST: "redis"
       REDIS_SERVICE_PORT: "6379"
       GRAPHITE_SERVICE_HOST: "graphite"
       GRAPHITE_SERVICE_PORT: "80"
       JENKINS_USER: "admin"
       JENKINS_PASSWORD: "targets-io"
       JENKINS_HOST: "http://jenkins:8080"
    restart: always
  mean:
    image: dmoll1974/targets-io-demo-meanjs
    ports:
     - "3001:3000"
    environment:
       DB_1_PORT_27017_TCP_ADDR: "db:27017"
    networks:
      - my-net
    restart: always

networks:
  my-net:
    driver: bridge

