targetsio:
  image: dmoll1974/targets-io
  ports:
   - "3000:3000"
  volumes:
   - .:/code
  links:
   - graphite
   - db
  environment:
     MONGO_SERVICE_HOST: "db"
     MONGO_SERVICE_PORT: "27017"
     GRAPHITE_SERVICE_HOST: "graphite"
     GRAPHITE_SERVICE_PORT: "80"
  mem_limit: 1000000000 
db:
  image: mongo:2.6.11
  ports:
   - "27017:27017"
  volumes:
   - /var/lib/targets-io/mongo:/data/db
  command: --smallfiles 
  mem_limit: 1000000000
graphite:
  image: dmoll1974/targets-io-graphite
  ports:
   - "8090:80"
   - "2003:2003"
   - "8125:8125"
  volumes:
   - /var/lib/targets-io/graphite/log:/var/log
   - /var/lib/targets-io/graphite/storage:/opt/graphite/storage
dropwizard:
  image: dmoll1974/targets-io-dropwizard
  ports:
   - "8080:8080"
  mem_limit: 1000000000
jmxtrans:
  image: dmoll1974/targets-io-jmxtrans
  links:
   - graphite
   - dropwizard
  mem_limit: 1000000000 
jenkins:
  image: dmoll1974/targets-io-jenkins
  ports:
   - "8070:8080"
  links:
   - graphite
   - dropwizard
   - targetsio
  mem_limit: 3000000000
